### ISSUE TITLE
Thymeleaf 3: Is loading the template four times really necessary?

### ISSUE THREAD

**Issue by tobiasflohre** [ultraq/thymeleaf-layout-dialect#108]
I'm checking the Snapshot implementation currently, and I found out that the template which is used to decorate (surround) our main template is loaded four times:

one time completely at DecoratorProcessor 92
one time with selector head at HtmlDocumentDecorator 72
one time with selector body at HtmlDocumentDecorator 101
one time with selector html at HtmlDocumentDecorator 119
Do you think that's necessary? Couldn't you clone the one loaded the first time? We have remote access for the template, so we have a little performance issue with that.

**Comment by ultraq** [comment]
Thanks for raising this.  Yes, the loading of a template 4 times seems totally unnecessary.  At the time I added those, it was the only way I knew how to obtain a model from a template, not knowing that it went through all of these Thymeleaf methods to reach out to template resolvers and everything else.

Now, I know how to pull out a sub-model from a model, so I'll be adding that to those areas you've identified.

Just curious: since this goes through the template manager, does turning the Thymeleaf cache on stop the excessing loading?

**Comment by tobiasflohre** [comment]
Each of those four loadings is done with a different cache key since the selector is included in the cache key. Of course, when the page is loaded the second time with caching turned on, we already have those four entries in the cache.
Thanks for adressing this! Tell me when it's included in the latest snapshot :-)

**Comment by ultraq** [comment]
Didn't think I'd be working on this for a while, but I came across something else that needed changes to how I fetch models, and so this got updated in the process 😁 

I've just uploaded another 2.0.0-SNAPSHOT, so that should reduce the crazy amount of template fetching that you found.

**Comment by tobiasflohre** [comment]
Thanks! Now I got https://github.com/ultraq/thymeleaf-layout-dialect/issues/110 ;-)
