### ISSUE TITLE
Don't include header elements more than once

### ISSUE THREAD

**Issue by pbauerochse** [ultraq/thymeleaf-layout-dialect#109]
First of all: Thanks for this beautiful dialect. It really helped me structure my app in separate layouts.
One thing I noticed though:

I have a base template with all my common js and css in the head section. In my content files that get included via your dialect, I might add some additional js / css only required for that specific page. This is all fine. But wenn I also add another css/javascript in the content file that already is included in the base template, it still gets added again, causing an unnecessary request to the server.

```html
<!-- base-template.html -->

<html>
<head>
    <script th:src="@{js/jquery.min.js}"></script>
</head>

<!-- content-file.html -->

<html layout:decorator="layout">
<head>
    <script th:src="@{js/jquery.min.js}" src="../js/jquery.min.js"></script> <!-- gets included again, would be nice if it wasn't -->
    <script th:src="@{js/just-for-content-file.js}" src="../js/just-for-content-file.js"></script> <!-- should be included for this page -->
</head>
```

I could just remove the duplicate include from the content file but then I could not test it in my browser without starting up the container (which actually is why I chose thymeleaf in the first place). Is there a way for you to detect whether that specific file was already included in the base template and simply skip it?

Cheers

Patrick

**Comment by ultraq** [comment]
Hey @pbauerochse, I'm glad you like this dialect 😊  Currently there is no way to detect and remove duplicates, so this might be something I can add in a future version.

As a solution though, you can add a `th:remove="tag"` to the `script` tag in your content page, so that when Thymeleaf processes it, it'll remove the duplicate.  Would that be enough to help here?

If not, then I'll have to have a think about what conditions an element will be considered a duplicate.  Given your example, I can't just compare element name and attributes (which would have been the easy solution!) since the content page has an extra `src` attribute.

**Comment by pbauerochse** [comment]
Yeah I figured it could be a bit complicated to detect that. But I think your ``th:remove="tag"`` solution might just be the answer to me. I was not aware of that tag so I'll give it a try. Thanks for your quick help

**Comment by SnakeSVx** [comment]
If you are using thymeleaf 2.1 or higher you could also use comments around the tags you don't want included in the output. If you have multiple lines this is usualy easier then putting th:remove="tag" everywere.

http://www.thymeleaf.org/whatsnew21.html#pocb (Prototype-only comment blocks).

**Comment by ultraq** [comment]
Looks like there are a few solutions you can use with plain old Thymeleaf, therefore I'll close this issue and not add anything to the layout dialect for it.
