### ISSUE TITLE
Decorator doesn't seem to work properly if decorating more then two layers (cascades > 2)

### ISSUE THREAD

**Issue by AlexKovalevich** [ultraq/thymeleaf-layout-dialect#121]
Based on previous thymeleaf and layout dialect I designed view that consists from 3-4 layers.

mainLayout.htm

````
<html>
<head>
    <meta>All common static js, charset etc. </meta>
    <link>All common css, etc</link>
    <title layout:fragment="headTitle"></title>
    <th:block layout:fragment="metaTags">Page specific metatags</th:block>
   <script type="text/javascript" layout:fragment="script">
       //custom js
    </script>
<head/>
<body id="top" layout:fragment="body" class="container-fluid" ...other attributes>
</body>
<html/>
````
On the second layer I have 3 different layouts as site has 3 different content types.
One o them is businessLayout.html
````
<html layout:decorate="~{/layout/mainLayout.html}">
<!--<head>-->
<!--</head>-->
   <body id="top" layout:fragment="body" class="business-section" > // business-section and 
container-fluid from mainLayout.html were properly merged in v1.x.

<th:block class="" layout:fragment="header" th:insert="~{/content/business/header_business.html :: html}">Header is not defined</th:block>
<div th:replace="/content/errors.html" />

<div class="container-fluid business-layout" layout:fragment="mainContent">
</div>
</body>
</html>
````
On the 3rd level it could be actual page like:
abouUs.html
````
<html layout:decorate="~{/layout/businessLayout.html}">
<div layout:fragment="mainContent">
        My awesome content
</div>
</html>
````

This structure worked perfectly fine.
After updating to 2.0.0 those templates get rendered into:

````
<html>
<!--<head>-->
<!--</head>-->

<body class="business-section" >

<div>Navigation header from th:insert="~{/content/business/header_business.html :: html}" </div>

<!DOCTYPE html >
<html>
This section comes from errors.html
</html>

<div class="container-fluid business-layout" >
        My awesome content
</div>
</body>
</html>
````
The issue is that mainLayout.html template is totally lost. businessLayout.html becomes root layer layout.
I think multilevel or cascaded decoration is standard feature, bu apparently it doesn't work in the new version of the dialect.

**Comment by ultraq** [comment]
Multi-level layouts is something I struggled with just before the release - I did manage to get it going for one existing test but not another, but I didn't want to let that stop the release.

Now that I've worked w/ Thymeleaf 3 a bit more, I think I have some idea of what I need to do to get this working again.  I think the 'automatically remove attribute processors' feature that Thymeleaf 3.0 added for dialect authors, while handy, is actually the cause of this because it automatically removes the second `layout:dialect` declaration after the first round of processing, thus losing your `mainLayout.html` and any further layout templates up the hierarchy that you've created.

This was one thing I really wanted to get fixed for 2.0.1, and I'll track it against this issue now.

**Comment by AlexKovalevich** [comment]
Kinda fixed !? 

Well, after playing with it for a while I found the following:
If I change constructor in DecorateProcessor from
`super(templateMode, dialectPrefix, null, false, attributeName, true, PROCESSOR_PRECEDENCE, **true**)`
to
`super(templateMode, dialectPrefix, null, false, attributeName, true, PROCESSOR_PRECEDENCE, **false**)`

then AbstractElementModelProcessor skips this section

```
            if (this.removeAttribute) {
                if (model.size() > 0 && model.get(0) instanceof IProcessableElementTag) {
                    firstEvent = (IProcessableElementTag) model.get(0);
                    final IModelFactory modelFactory = context.getModelFactory();
                    final IProcessableElementTag newFirstEvent = modelFactory.removeAttribute(firstEvent,attributeName);
                    if (newFirstEvent != firstEvent) {
                        model.replace(0, newFirstEvent);
                    }
                }
            }

```
which prevents from recursive template processing.

I also had to comment out this section in DecorateProcessor not to throw exceptions when root html becomes not root when gets processed by it's parent..

```
		// Ensure the decorate attribute is in the root element of the document
		//if (context.elementStack.size() != 1) {
		//	throw new IllegalArgumentException('layout:decorate/data-layout-decorate must appear in the root element of your template')
		//}

```

So those two changes appear to fix the issue with recursive processing.
I hope it will help you to implement proper fix.

**Comment by ultraq** [comment]
After messing around with things, the fix turned out to be really simple.  I changed the 'auto remove processor' flag from `true` to `false` just like you did, and then all I had to do was fix the code for making sure that the `layout:decorate`/`data-layout-decorate` processor was in the root, or in this case making sure that every processed element in the stack has a decorate processor.  You can check the changes in the commit that's linked to this issue just above this comment to see the changes, including the test I re-enabled to make sure it works.

I've uploaded a new 2.0.1-SNAPSHOT version, so could you give that a try, see if the changes have helped you out with your multi-level layouts?

**Comment by AlexKovalevich** [comment]
Tested with snapshot thymeleaf-layout-dialect-2.0.1-20160717.014735-4.pom - everything looks awesome! I don't see any functional issues at all.

**Comment by ultraq** [comment]
Good to hear! 😀
