### ISSUE TITLE
th:switch with title tag doesn't work

### ISSUE THREAD

**Issue by tanyona** [ultraq/thymeleaf-layout-dialect#133]
I'm trying to set a dynamic page title depending on the value of a model attribute (same page is used for add and edit functions).

Sample **layout.html**
```html
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" xmlns:th="http://www.thymeleaf.org"
	  xmlns:layout="http://www.ultraq.net.nz/thymeleaf/layout">
	<head>
		<title layout:title-pattern="$LAYOUT_TITLE - $CONTENT_TITLE">Test</title>
		<meta charset="UTF-8"/>
	</head>
	<body>
		<div>TODO write content</div>
	</body>
</html>
```

Sample **test.html**
```html
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" xmlns:th="http://www.thymeleaf.org"
	  xmlns:layout="http://www.ultraq.net.nz/thymeleaf/layout"
	  layout:decorate="~{layout}">
	<head>
		<th:block th:switch="${action}">
			<title th:case="'add'" th:text="${'adding'}">Add User</title>
			<title th:case="'edit'" th:text="${'editing'}">Edit User</title>
			<title th:case="*" th:text="${action}">Title</title>
		</th:block>
	</head>
	<body>
		<div>TODO write content</div>
	</body>
</html>
```

Sample **Controller.java**
```java
@GetMapping("/test")
	public String success3(Model model) {
		model.addAttribute("action", "edit");
		return "test";
    }
```

The effect is that the page title when navigating to /test is always **Test - adding** i.e. the first case statement is always picked even when the action passed is "edit". This is the resulting page source..
```html
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
	<head>
		<title>Test - adding</title>
		<meta charset="UTF-8"/>
	
			
			<title>editing</title>
			
		
	</head>
	<body>
		<div>TODO write content</div>
	</body>
</html>
```
Is there something I'm doing wrong?

**Comment by ultraq** [comment]
Hi @tanyona, you're not doing anything wrong there.  When performing the decoration process, the layout dialect searches for the first `title` tag and tries to extract the value of it, either from a `th:text` attribute or the text within the opening and closing tags, and then saves that as the title for that page.  Because of that, your switch statement doesn't get the chance to influence the resulting title.

As a workaround, I think you could condense your switch statement to fit within a single `th:text` attribute like below, and the layout dialect will see that expression and use it as the value for the title.

```html
<title th:text="${action} == 'add' ? 'adding' :
                ${action} == 'edit' ? 'editing' :
                ${action}">Title</title>
```

**Comment by tanyona** [comment]
Thanks for the clarification. The code you provided will suite my needs..
