### ISSUE TITLE
how to use data-layout-insert

### ISSUE THREAD

**Issue by dongwenting** [ultraq/thymeleaf-layout-dialect#135]
I use thymeleaf-layout-dialect 2.0, and I add this to the layout html's body, but the result is empty.
how to add content html' title to the result html? thx~~~

```
     <span data-layout-insert="::title"> </span>
```

**Comment by ultraq** [comment]
When using a fragment expression with the layout dialect, it looks for instances of `layout:fragment` to match on, so your fragment expression of `::title` will look for `layout:fragment="title"` rather than the HTML `<title>` element.

I'll have to double-check against Thymeleaf to see what it would do for such a fragment expression, but if you're after the title that the page will have as the result of using the layout dialect, then a workaround might be to use the special `layout.resultingTitle` value that is accessible in any template.  From the [Configuring your Title](https://ultraq.github.io/thymeleaf-layout-dialect/Examples.html#configuring-your-title) section in the docs:

> As of 1.3.0, the resulting title is accessible via `layout.resultingTitle`.
> `layout` is a special object added by this dialect (just like how Thymeleaf
> adds `session`, `param`, and `application` objects), to expose some internals.
> Right now, `resultingTitle` is the only value on this object.

**Comment by dongwenting** [comment]
Thank you for your answer. I add this to layout html, it works.     
      <span th:text="${layout.resultingTitle}"> </span>

but I don't need the whole result title, just the content's title.

     Content.html
     <head>
              	<title layout:fragment=“title”> content title </title>
     </head>

      Layout.html
     <head>
              	<title layout:title-pattern="$LAYOUT_TITLE - $CONTENT_TITLE"> layout title </title>
     </head>
     <body>
             title1: <span th:text="${layout.resultingTitle}"> </span>
             title2: <span data-layout-insert="::title"> </span>
      </body>

      Result.html
      <head>
              	<title> layout title - content title</title>
     </head>
     <body>
             title1: <span> layout title - content title </span>
             title2: <span> </span>
      </body>

       I expect title2 is "content title", how to do that ? thx

**Comment by ultraq** [comment]
Hmm, how about if you tried using the standard `th:insert`/`data-th-insert` instead of `layout:insert`?

If that doesn't work, then I may need to expand the layout dialect to include the separate parts of the title, content and layout, as well as the result.

**Comment by ultraq** [comment]
Haven't heard from you for a while @dongwenting, but I've gone and added new `layout.contentTitle` and `layout.layoutTitle` properties on the `layout` special object that contain the content and layout template titles respectively.  This is in version 2.1.0 of the layout dialect which I've just released today.

If the previous workarounds I gave haven't helped, then I hope those help in some way too.
