### ISSUE TITLE
Memory leak: ExpandoMetaClass' retaining old gen heap with weakrefs

### ISSUE THREAD

**Issue by gheylen** [ultraq/thymeleaf-layout-dialect#139]
# Context:
In-development news site for biggest Belgian brand using Thymeleaf + this decorator provided and suggested by Spring Boot.

# Problem statement:
Old-gen heap is overrun by Groovy - classes from this decorator. 

![acc_with_thymeleaf_layoutdialect_2 0 4_throughput_130s_markup_github](https://cloud.githubusercontent.com/assets/3791719/19433415/df388e22-9460-11e6-9b42-85478df2217d.png)

![acc_with_thymeleaf_layoutdialect_2 0 4_leak_suspects](https://cloud.githubusercontent.com/assets/3791719/19433423/e6138d3c-9460-11e6-9676-9db302cf87ff.png)

![acc_with_thymeleaf_layoutdialect_2 0 4_biggest_dominator_classes](https://cloud.githubusercontent.com/assets/3791719/19433459/1ac1acb2-9461-11e6-8096-3e057ddfcde2.png)

# Short-term solution provided
Removal of this layout decorating dependency and using core thymeleaf includes where needed.

![acc_without_thymeleaf_layoutdialect_throughput_230s_with_markup_github](https://cloud.githubusercontent.com/assets/3791719/19433867/cd9ae00a-9462-11e6-8279-689e05838542.png)

# Long-term solution expectations
Finding and fixing this memory leak so we can use  this great layout decorator. Has anyone been having the same issue?

**Comment by ultraq** [comment]
How timely - I'm working on memory and performance improvements at this very second and doing some profiling to see how it's all going 😁  I've got a general performance GitHub issue over at #102, and the first item I was tackling was the memory thing as previous issues raised and fixes made around them have shown some really good gains.

To answer your question though: yes, other people have been seeing similar things (see #122), and I've been able to tackle them on a case-by-case basis to the point of being good enough for the use case of the person raising the issue, but just now I'm taking another view of the whole thing to find out where some more gains can be made.

### The current (release) state of things

I've developed a simple test project over the course of the memory issues that uses a basic layout and every dialect feature in it, that I then hit with JMeter to simulate continuous load.

Libraries:
 - thymeleaf-3.0.2.RELEASE
 - thymeleaf-spring4-3.0.2-RELEASE
 - spring-context.4.3.3.RELEASE
 - spring-web-4.3.3.RELEASE
 - spring-webmvc-4.3.3.RELEASE

Using 2.0.4, the current latest version of the layout dialect:

![screen shot 2016-10-17 at 11 15 47 pm](https://cloud.githubusercontent.com/assets/1686920/19434020/b86d9d3c-94bf-11e6-9c69-355ee726232a.png)

Main takeaways:
 - old generation space at 99MB used at the end of the test
 - `groovy.lang.ExpandoMetaClass` having a retained size of ~52MB
 - 27 million objects created
 - 35 garbage collections over the course of the test
 - test took about 3 minutes 10 seconds to complete (started around the 30 second mark)

### An in-development state of things

I've just uploaded a 2.1.0-SNAPSHOT which, as per my comment on the general performance GitHub issue:

> removed more uses of dynamic objects/classes as a follow-through of #122, taken to the extreme

Results:

![screen shot 2016-10-17 at 11 27 26 pm](https://cloud.githubusercontent.com/assets/1686920/19434342/559107c4-94c1-11e6-84a1-546894639ad4.png)

Main takeaways:
 - old generation space at 21MB at the end of the test (~80% improvement)
 - `groovy.lang.ExpandoMetaClass` having a retained size of ~119KB (~99.99...% improvement!!!  I had to scroll to find the item on the list as it wasn't even in the first page of results any more!)
 - 6.6 million objects created (~75% improvement)
 - 20 GCs over the course of the test (~40% improvement)
 - test took about 1 minute to complete (~66% improvement.  I ran this test 3 more times and even restarted all the tools just to make sure I wasn't screwing something up!)

I've got several more things to work on, so these are the results **as of posting**.  Future snapshots may be better or worse, but I expect them to hover around these results since it looks like one of the worst performance offenders was tackled.

If you, or anybody watching this repo, would like to try out the performance improvements, then feel free to put the 2.1.0-SNAPSHOT branch into your project and please report your results.

**Comment by gheylen** [comment]
Thanks for quick response, E.

Could you push the 2.1.0-SNAPSHOT - branch? We can't locate it. We'll put it through exactly the same stress test which gave above results.

**Comment by ultraq** [comment]
Heya, I'm gonna be away from the computer that has that code for the next day (maybe it'll feel like 2 in your timezone), so can't push the source code branch 😞  I did however upload the artifact to Maven, so if you configure Maven/Gradle for snapshot repositories and pick the `2.1.0-SNAPSHOT` version, you should be able to add it to your project to test.

Alternatively, the Maven snapshot repository can be navigated with your browser so you can download the built artifact here: https://oss.sonatype.org/content/repositories/snapshots/nz/net/ultraq/thymeleaf/thymeleaf-layout-dialect/2.1.0-SNAPSHOT/thymeleaf-layout-dialect-2.1.0-20161017.092221-3.jar

**Comment by ultraq** [comment]
Did you manage to get the snapshot version working on your project without the source code?  Otherwise, I'm finally home and have managed to upload the in-development performance improvements to a `performance` branch which you can check out here: https://github.com/ultraq/thymeleaf-layout-dialect/tree/performance

**Comment by gheylen** [comment]
We put the 2.1.0-SNAPSHOT through the same set of tests. 

![acc_with_thymeleaf_layoutdialect_2 1 0-snapshot_throughput_170s_markup](https://cloud.githubusercontent.com/assets/3791719/19519786/a807fc86-960d-11e6-9a41-78354066a902.png)

Results above. We can see a significant improvement, which confirms your claims. Young gen, survivor, and old gen all remain stable.

**Comment by gheylen** [comment]
Any idea when you're releasing?

**Comment by ultraq** [comment]
Woohoo!  That's good news 😀

As for when there'll be an official 2.1.0 release, that will be at least 2 weeks away - there's a 2.0.5 bug fix version I'm working on now, and several more general performance-related ideas I want to try get in as per the other GitHub issue I linked to before.  I'll be keeping the snapshot version updated with all main branch fixes, but it is still a while away.

**Comment by ultraq** [comment]
FYI, I've just released 2.1.0 today.
