### ISSUE TITLE
Version 2.1.2 title layout:title-pattern problem

### ISSUE THREAD

**Issue by flashing** [ultraq/thymeleaf-layout-dialect#145]
After upgrading to thymeleaf 3.0.2 and thymeleaf-layout-dialect 2.1.2,
layout:title-pattern doen't work with expression.
This 
<title layout:title-pattern="$CONTENT_TITLE - $DECORATOR_TITLE" th:inline="text">[[${@environment.getProperty('spring.application.name')}]]</title>
works with spring boot 1.4.2 thymeleaf 2.x and layout-dialiect 1.x, not complicated with latest version, I also tried $LAYOUT_TITLE but doen't work either.
Would anyone please help me with this?

**Comment by ultraq** [comment]
What are you getting instead of your expected result?  I just tried it out and it ended-up not substituting the inlined expression, which I guess is what you expected?

Looks like this might be a bug with the 2.x branch as I don't have a test for inlined expressions in titles.

Since the problem is with inlined expressions, a workaround is to put the inline expression into a `th:text` one, eg:

```html
<title layout:title-pattern="$CONTENT_TITLE - $LAYOUT_TITLE" th:text="${@environment.getProperty('spring.application.name')}"></title>
```

FYI, you might be able to get rid of `th:inline="text"` expressions in your templates when upgrading to Thymeleaf 3.  The migration guide mentions that inlining is available everywhere without the need for the `th:inline` processor any more.  See https://github.com/thymeleaf/thymeleaf/issues/394 for details.

**Comment by flashing** [comment]
Yes, this is exactly what I wanted, thank you very much!
I know th:inline should be got rid of and I have tried but it didn't work properly so I post the original code here.
Thanks again for your help.

**Comment by ultraq** [comment]
I've uploaded a 2.2.0-SNAPSHOT version with the fix to this bug.  I've also uploaded some new tests to cover this, but if you could give that version a try with your projects, see if it works for you, then that'd be helpful too.
