### ISSUE TITLE
Nested decoration

### ISSUE THREAD

**Issue by hiddewie** [ultraq/thymeleaf-layout-dialect#149]
I am trying to decorate a page with a template. The template I decorate is again decorating another template, my base template. 

This way I can make a tree structure of the template pages, like below:
- `base.html`
  - `extra_menu.html`
    - `template.html`

At the moment, when I render `template.html`, I only get the HTML content of `extra_menu.html`, but not of the base template `base.html`. 

Is this desired? At the moment I would have to include every fragment of the `base.html` template by hand in `extra_menu.html` to let the page render correcly.

**Comment by ultraq** [comment]
Even though the layout dialect was originally designed with just 1 layout template in mind, devs have managed to use it for multiple templates each decorating each other to achieve the desired result.  I do have test cases for 2 layout templates (or 3 levels of templates) just like in your example, so it should be able to handle it.

Are you able to provide an example that's close to your use case and doesn't work?  (Example templates help me out a lot since I can then debug what's going on.)

I also have a few Thymeleaf test files that test 3 levels of templates (eg: https://github.com/ultraq/thymeleaf-layout-dialect/blob/master/Tests/nz/net/ultraq/thymeleaf/tests/decorators/Decorate-DeepHierarchy.thtest), but I'm guessing that test file is nothing like what you're trying to put together?

**Comment by hiddewie** [comment]
Thanks for the quick response. 

My example is actually a lot like `Decorate-DeepHierarchy.thtest` (I did not see that test before), so it should work in theory. I will experiment a little bit and find the differences between my template and the test template structure to find the problem in more detail.

**Comment by hiddewie** [comment]
I've debugged my example to a minimal setup: 

Template:
```html
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" xmlns:th="http://www.thymeleaf.org" xmlns:layout="http://www.ultraq.net.nz/thymeleaf/layout" layout:decorate="~{common/leftmenu_layout}">
<head>
</head>
<body>
<div layout:fragment="content">
	CONTENT
</div>
</body>
</html>
```

`common/leftmenu_layout.html`:
```html
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" xmlns:th="http://www.thymeleaf.org" xmlns:layout="http://www.ultraq.net.nz/thymeleaf/layout" layout:decorate="~{common/base}">
    <head>
    </head>
    <body>
        <div layout:fragment="wrapper">
            PARENT
            <div layout:fragment="content"></div>
        </div>
    </body>
</html>

```

`common/base.html`
```html
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" xmlns:th="http://www.thymeleaf.org" xmlns:layout="http://www.ultraq.net.nz/thymeleaf/layout">
    <head>
    </head>
    <body layout:fragment="body">
    GRAND PARENT
    <div layout:fragment="wrapper">
        NORMAL WRAPPER
    </div>
    </body>
</html>
```

Rendered HTML: 

```html

<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
    
    </head>
    <body>
        <div>
            PARENT
            <div>
	CONTENT
</div>
        </div>
    </body>
</html>
```

It looks a lot like the test, so I do not understand why this does not work. My Thyemleaf is version `3.0.0.RELEASE`, with the `spring4` extension. The Layout dialect is version `2.0.0`.

**Comment by hiddewie** [comment]
I think the issue has been resolved by simply upgrading to the Layout dialect version `2.1.2`. Sorry for the disturbance.

**Comment by ultraq** [comment]
Oh cool, good to now that a fix was already there for you! 😃  And no worries about the raising of the issue - I'd rather know about any problems and have the option to fix things rather than have developers just grumble that it's not working for them.

**Comment by 40rn05lyv** [comment]
@hiddewie thanks for your solution.
