### ISSUE TITLE
layout stops working when spring.thymeleaf.mode=LEGACYHTML5

### ISSUE THREAD

**Issue by kgignatyev** [ultraq/thymeleaf-layout-dialect#150]
I had to switch to spring.thymeleaf.mode=LEGACYHTML5 to allow content with 'naked' attributes, and as soon as I did that layout stopped to.

**Comment by ultraq** [comment]
Hi @kgignatyev, are you able to provide a small example of the layout not working?

Thymeleaf 2 in its LEGACYHTML5 mode is notorious for producing the wrong results because of the reliance on an external tag balancing library, nekoHTML, for trying to produce a valid XML document and getting things wrong in the process.  An example of this failing helps because for some templates it works, but for other templates with slightly different combinations of HTML boolean attributes and "null" tags it doesn't.

A possible workaround is if you're able to upgrade to Thymeleaf 3 at all?  It makes use of its own parsing library that can handle HTML natively without having to resort to tag balancing, and version 2 of the layout dialect works quite well with it too.

**Comment by kgignatyev** [comment]
Thank you!
You are correct. springboot includes version 2 by default, after setting versions in properties for the project it works now
 <properties>
....
       <thymeleaf.version>3.0.3.RELEASE</thymeleaf.version>
        <thymeleaf-layout-dialect.version>2.0.5</thymeleaf-layout-dialect.version>

    </properties>

**Comment by ultraq** [comment]
Glad to hear you could move to Thymeleaf 3 and that it solved your problem!
