### ISSUE TITLE
Warning generated by Thymeleaf when using nz.net.ultraq.thymeleaf.expressions.ExpressionProcessor

### ISSUE THREAD

**Issue by AndrewRichardScully** [ultraq/thymeleaf-layout-dialect#159]
Hi,

I get the following warning printed at startup, I think it's being generated because the Thymeleaf 3 is taking exception to the ExpressionProcessor:

12468/0|2017-06-06 11:49:25,115 WARNING [nz.net.ultraq.thymeleaf.expressions.ExpressionProcessor] (58,http-listener-2(5)) Fragment expression "layout" is being wrapped as a Thymeleaf 3 fragment expression (~{...}) for backwards compatibility purposes.  This wrapping will be dropped in the next major version of the expression processor, so please rewrite as a Thymeleaf 3 fragment expression to future-proof your code.  See https://github.com/thymeleaf/thymeleaf/issues/451 for more information.

Is anyone able to confirm whether the warning is being printed because of thymeleaf-layout-dialect
 ?

Kind Regards,
Andrew Scully.

**Comment by ultraq** [comment]
Yup, that's coming out of expression processor, which is used by the layout dialect under the hood to parse/process expressions.  One of the other jobs it is doing is, as per the warning message, wrapping values given to some of the processors, like the values that go into `layout:decorate`, with `~{...}` so that they are valid fragment expressions.

So in older versions of the layout dialect and Thymeleaf, you could go: `layout:decorate="layout"`, but since Thymeleaf 3 any values that reference fragments or templates should now be fragment expressions (`layout:decorate="~{layout}"`) as per the GitHub issue/link logged in the warning.  Future major releases of the expression processor and layout dialect (and eventually Thymeleaf, although I don't know when it will decide to do it) will drop support for the non-fragment expressions.
