### ISSUE TITLE
Couldn't run if style include two classes(one of them is a expression).

### ISSUE THREAD

**Issue by pengcheng789** [ultraq/thymeleaf-layout-dialect#160]
Hi,my \<li\> style has a necessary classes "dropdown",and I want to use the following usage to add one class:
```
<li th:class="dropdown ${page eq 'home'} ? active">
    ...
</li>
```
And then it couldn't run.
Could you tell me what should I do?Thanks!

**Comment by ultraq** [comment]
Hi there @pengcheng789.  This isn't really a layout dialect issue, but I can help a bit.

There's a Thymeleaf `th:classappend` processor that you can use for this case.  Put the `dropdown` in a plain old `class` attribute since you always want that, then use `th:classappend` with your expression to add it during processing, eg:

```html
<li class="dropdown" th:classappend="${page} == 'home' ? 'active'">
```

(Hope that my expression language syntax is correct!)

Docs on `th:classappend`: http://www.thymeleaf.org/doc/tutorials/3.0/usingthymeleaf.html#appending-and-prepending

**Comment by pengcheng789** [comment]
Aha!It seems I made a mistake.Thank you!
