### ISSUE TITLE
Updating groovy:jar 

### ISSUE THREAD

**Issue by ammy1999** [ultraq/thymeleaf-layout-dialect#164]
Hello, 
I have a vulnerability groovy-2.4.10.jar , CVE-2016-6497 , Severity: Medium ( plugin dependency check in jenkins) 

When I run mvn dependency:tree -X : 

> +- nz.net.ultraq.thymeleaf:thymeleaf-layout-dialect:jar:2.2.2:compile
[INFO] |  \- org.codehaus.groovy:groovy:jar:2.4.10:compile
 
So how can I remove this vulnerability

**Comment by ultraq** [comment]
Weird, this project brings in 2.4.6 (https://github.com/ultraq/thymeleaf-layout-dialect/blob/master/build.gradle#L54), so I don't know what's in your build to have chosen 2.4.10?  Anyway, I read up on the vulnerability from the original research paper and don't believe this library or your project are at risk.

From what I can gather, CVE-2016-6497 is about remote code execution through LDAP implementations in the JVM, and one example of this was with a product called Apache Directory via a Groovy LDAP API.  Since being told of this vulnerability, Apache have removed the Groovy LDAP API from their product.

Here's the paper and the relevant quote:
https://www.blackhat.com/docs/us-16/materials/us-16-Munoz-A-Journey-From-JNDI-LDAP-Manipulation-To-RCE-wp.pdf

> **Example: Apache DS Groovy API**
> Apache Directory offers a wrapper class (org.apache.directory.groovyldap.LDAP) which provides LDAP functionality to Groovy. This class uses the  _returnObjFlag_ set to _true_ for all search methods and thus renders them vulnerable to LDAP Entry Poisoning.
> 
> **Disclosure Timeline:**
> The vulnerability was responsibly disclosed to Apache who decided to remove the Groovy API from its site (still available in cache: http://web.archive.org/web/20160702093242/http://directory.apache.org/api/groovy-ldap.html) and release.
> 
> 24/Jun/2016 - Initial report of the vulnerability.
> 
> 07/Jul/2016 - Apache removes the Groovy API from the web site and announce that it was not part of the release

So the vulnerable code in question was in a pre-release version of Apache Directory, and not Groovy itself.  The affected file, `org/apache/directory/groovyldap/LDAP.java` does not exist in the Groovy JAR imported by this project.

If you want to double-check my findings, I found this site was a good resource since it had links to everything I mentioned: https://nvd.nist.gov/vuln/detail/CVE-2016-6497

**Comment by ammy1999** [comment]
groovy 2.4.10 (managed from 2.4.6) 
So what should I do , the vulnerability with high priority

**Comment by ultraq** [comment]
Given what I've discovered, I believe this is a false positive report of the Groovy JARs, so I've gone and filed a false positive report on the dependency check library that the Jenkins plugin uses (https://github.com/jeremylong/DependencyCheck/issues/1004.  For now, I would suggest you suppress this warning, which you can read on how to do over on the dependency check plugin's website: https://jeremylong.github.io/DependencyCheck/general/suppression.html

**Comment by ammy1999** [comment]
How can I suppress this warning ?? I check the source code of dependency check plugin , I found the file suppression.xml  , So the suppression isn't  automatically done !!

**Comment by ultraq** [comment]
Given the documentation in the link I gave you in my last reply, it seems you can do this from a button in the HTML report:

> Suppressing these false positives is fairly easy using the HTML report. In the report next to each CPE identified (and on CVE entries) there is a suppress button. Clicking the suppression button will create a dialogue box which you can simple hit Control-C to copy the XML that you would place into a suppression XML file. If this is the first time you are creating the suppression file you should click the “Complete XML Doc” button on the top of the dialogue box to add the necessary schema elements.

I suggest reading that doc - it looks fairly comprehensive.

**Comment by ammy1999** [comment]
yes , finally it works , thanks @ultraq  for your help
