### ISSUE TITLE
layout:decorate not properly merge xmls in 2.2.2

### ISSUE THREAD

**Issue by kowalczm** [ultraq/thymeleaf-layout-dialect#169]
layout.xml
```
<a xmlns:layout="http://www.ultraq.net.nz/thymeleaf/layout">
	<b>
		<c layout:fragment="testFragment" />
	</b>
</a>
```
page.xml
```
<a xmlns:layout="http://www.ultraq.net.nz/thymeleaf/layout"
	layout:decorate="~{layout}">
	<b>
		<c layout:fragment="testFragment">
			<d>test</d>
		</c>
	</b>
	<e>outer</e>
</a>
```
result:
```
<a>
	<b>
		<c>
			<d>test</d>
		</c>
	</b>
</a>
```
I would expect  also`<e>outer</e>`.
The same situation is for replacing.
I'm using Thymeleaf: 3.0.9

**Comment by ultraq** [comment]
Well that definitely doesn't look right.  Will investigate - thanks for letting me know!

**Comment by kowalczm** [comment]
Hi,
Is there any plan for next release in near future? I see latest from May 2017 and few relevat changes like in test: Document-XmlDecoration-MultipleElements-Nested.thtest

**Comment by ultraq** [comment]
Maybe one after this issue if I find it's relatively easy to fix?  Otherwise, if you want to use all the newest code since the last release, you can always use the SNAPSHOT release (currently `2.3.0-SNAPSHOT`).

**Comment by ultraq** [comment]
I finally had a closer look and found that I had misread your post (sorry!), and so what you've got is expected behaviour.

When you pick file to decorate (the layout), what you're doing is saying that you'll take that layout and only replace bits and pieces picked out by `layout:fragment` parts in the layout.  Anything outside of `layout:fragment` elements in your content page will not end up in the result unless specifically asked for by the layout.

There's a note in the [Examples > Layouts](https://ultraq.github.io/thymeleaf-layout-dialect/Examples.html#layouts) section of the docs that mentions this (although it's talking about HTML files):

> The decoration process redirects processing from your content template to the
> layout, picking `layout:fragment` parts out of your content template as the
> layout demands them.  Because of this, anything _outside_ of a `layout:fragment`
> within the `<body>` in your content template never actually gets executed [...]

In your case, `<body>` is the entire XML document.

If you want your pages to have optional bits and pieces in the result, then you'll need to provide the necessary extension points in your layout.  Updating your example:

```xml
page.xml
<a layout:decorate="~{layout}">
  <b>
    <c layout:fragment="testFragment">
      <d>test</d>
    </c>
  </b>
  <e layout:fragment="extra">outer</e>
</a>

layout.xml
<a xmlns:layout="http://www.ultraq.net.nz/thymeleaf/layout">
  <b>
    <c layout:fragment="testFragment" />
  </b>
  <e layout:fragment="extra" th:remove="tag"/>
</a>
```

(You can shorten the `<e ... th:remove="tag">` to a `<th:block>` element instead, a special element that Thymeleaf takes the tag out, but not the contents: http://www.thymeleaf.org/doc/tutorials/3.0/usingthymeleaf.html#synthetic-thblock-tag)

**Comment by kowalczm** [comment]
Hmm, so why in [https://ultraq.github.io/thymeleaf-layout-dialect/Examples.html#layouts] result html contains two <script> tags? According above only <script> tag from  layout should be taken. There are different implementation for HTML?

**Comment by ultraq** [comment]
Yup, there is some special handling of the `<head>` section for HTML mode because merging of that section is such a common use case that it's got some of its own rules about what happens there.  The `<body>` section is more general, just like XML mode, and the 2 are pretty much the same.
