### ISSUE TITLE
Render problem in HTML <head>

### ISSUE THREAD

**Issue by BeRoots** [ultraq/thymeleaf-layout-dialect#176]
I have some problem with thyleafeaf-layout-dialect usage into spring-boot-2.0.3 application. The problem is that the `<meta charset="UTF-8" />` isn't the first element in my <head> but i declaring it in the first position in my layout.html. (see https://github.com/BeRoots/springboot2-demo-thymeleaf-layout)

If you have an idea about it.

**Comment by ultraq** [comment]
Hi there, so the code that deals with working on the `<head>` element currently always puts the `<title>` as the first element, which is why your `<meta charset...` tag isn't ending up first.

It's been a while since I worked on that particular piece, but this feels like an abitrary decision I made so that processing of the `<head>` section is easier (separating all the special `<title>` processing from the rest of the elements make the code simpler).  The end result is still logically correct, but I'm guessing you want your `<meta>` tag first for a reason?

**Comment by BeRoots** [comment]
Hi. Simply because it's a w3c recommendation to have valid code. https://www.w3.org/International/questions/qa-html-encoding-declarations.en#quickanswer

But I do not see this constraint to have the presence of the meta "charset" in the first 1024 bit in the dedicated specification. https://www.w3.org/TR/2010/WD-html-markup-20100304/meta.charset.html

Personally I think your idea is not so good. Indeed as much for this case with "charset" as for example with the tag <script> of google analitics which is imposed at the beginning of the head section. Choosing the last of this section it's for me a better way and respect css and js head overriding by the view too.

It is possible for me to change this feels ?

**Comment by ultraq** [comment]
Right now you can't change this behaviour.  I agree that it'll be better to try preserve the order of elements (unless the `<head>` element merging strategy is configured to do something different) rather than arbitrarily making the choice of re-ordering a dev's markup.

If your `<title>` text isn't long, then the `<meta charset...` should still be within the first 1024 bytes of the response, so I think that only in very specific cases will the `<meta charset...` fail to be read by the browser and the incorrect document encoding applied.

I'll raise a new issue for changing this behaviour, and post in here too so you can be informed of when it's done.

**Comment by perry-ugroop** [comment]
Hi, may I add that aside from the fact that placing the &lt;meta charset&gt; tag *right after* &lt;head&gt; and before &lt;title&gt; is the standards-compliant way to do it, *not* following this specific order would also place the website at risk of exposure to [UTF-7 XSS attacks](https://www.html5in24hours.com/meta-charset-protects-against-hackers/). Placing &lt;meta charset&gt; within the first 512 bytes of the HTML document *guarantees* that the character set will be enforced throughout the document (and will thwart the UTF-7 hack for fooling the browser's encoding), while placing the meta charset tag further away from 512 bytes no longer guarantees it.

**Comment by perry-ugroop** [comment]
May I also add, FWIW, according to the [XHTML 1.0 Strict DTD](https://www.w3.org/TR/xhtml1/dtds.html#dtdentry_xhtml1-strict.dtd_title), *exactly one* &lt;title&gt; and *at most one* &lt;base&gt; tag should be present inside the &lt;head&gt; tag. This could help you in your &lt;head&gt;-merging logic.

**Comment by ultraq** [comment]
I've updated the layout dialect and introduced 2 new sorting strategies that respect the position of the `<title>` element in the layout template:
 - `nz.net.ultraq.thymeleaf.decorators.strategies.AppendingRepsectLayoutTitleStrategy`
 - `nz.net.ultraq.thymeleaf.decorators.strategies.GroupingRepsectLayoutTitleStrategy`

The names are a bit long for now, but that's because I'm keeping the old ones around to stay backwards compatible with the 2.x versions of the layout dialect.  These will replace the now deprecated `AppendingStrategy` and `GroupingStrategy` classes in the next major version, 3.x.

The docs have been updated to include all the details: https://ultraq.github.io/thymeleaf-layout-dialect/Configuration.html  The `2.4.0-SNAPSHOT` version has also been updated with these changes.
