### ISSUE TITLE
css class from content template div gets assigned to main layout html tag as well

### ISSUE THREAD

**Issue by vk011** [ultraq/thymeleaf-layout-dialect#187]
Hi,

I have one main layout page, the relevant code is this:
```
<section layout:fragment="content">
    <p>Page content goes here</p>
</section>
```
And I have just one content template, the whole file goes like so:
```
<div class="container" layout:decorate="~{_layouts/main}" layout:fragment="content">
    home
</div>
```
The problem is, the `container` class from the content template div gets assigned to the `html` tag in the main layout as well for some reason ?

![Capture](https://user-images.githubusercontent.com/16360732/56244659-b4be1980-609d-11e9-967d-d6a31f4beb1f.JPG)

**Comment by ultraq** [comment]
Yes, the attributes from the `layout:decorate` do get copied over to the target element.  I don't think this is documented though (closest thing I can find is a recent note here: https://ultraq.github.io/thymeleaf-layout-dialect/Examples.html#passing-data-to-layouts), but this has probably been around since the beginning when Thymeleaf was a bit more limited in supported template types (ie: when it *had* to have a root element like `<html>`) and didn't yet support passing data between fragments, so this was a handy way to get around that (eg: setting IDs or class names on elements from the content to the layout).

The workaround would be to create more elements to split the `layout:decorate` and `class` attributes out so they don't get included in the process, eg:

```html
<html layout:decorate="~{_layouts/main}">
  <div layout:fragment="content" class="container">
```

I'll document this behaviour some time, and also have a think about whether the behaviour should be configurable.
