### ISSUE TITLE
Unable to load the complete layout while adding a new html file

### ISSUE THREAD

**Issue by navindercsb15** [ultraq/thymeleaf-layout-dialect#190]
I am facing an issue while adding a new html file, it is working fine with other pages which dynamic changes the content in the th:fragment="content", but when I add a new page complete layout is not being inherited, example CSS and many script. Please resolve this issue.
![image](https://user-images.githubusercontent.com/31277782/63231131-bf97df00-c234-11e9-8925-058b0a0d9ab9.png)

And when a new file is added with same layout:decorate, below problem arises
![image](https://user-images.githubusercontent.com/31277782/63231140-e6eeac00-c234-11e9-98dd-d684177e58aa.png)

**Comment by ultraq** [comment]
Hi there, are you able to provide either:
 - the HTML of the content and layout pages where you're facing the issue?
 - or the HTML of a minimum layout and content that can also reproduce your issue?

I can better help if you're able to provide an example where I can see the problem happening, or enough information so I can reproduce the issue on my own machine.

**Comment by navindercsb15** [comment]
Can I share you the project in your mail? It is too large. I will be great full if you resolve my issue sooner.

**Comment by navindercsb15** [comment]
Or I am uploading it in my repo, I will share the link with you.

**Comment by navindercsb15** [comment]
https://github.com/wesmarty/SpringBootIssueWithThymeleaf.git

Hello Sir. I have shared the git link with you. Please look into the issue

**Comment by ultraq** [comment]
I spun up the project in your link and when I opened your test page I saw in my browser dev tools lots of 404s to your JS/CSS resources.  It looks like the issue is a relative path problem.  Your `layout.html` file has lines that looked like this:

```html
<link rel="stylesheet" th:href="@{dist/css/ChemPlace.min.css}">
```

That means to look for that file *relative* to your current page.  So when you'd open the test page on your machine at `http://localhost:5000/`, the full path to the resource becomes `http://localhost:5000/dist/css/ChemPlace.min.css`.  But when you open the test page on another URL like `http://localhost:5000/testing/`, then the full path to the resource becomes `http://localhost:5000/testing/dist/css/ChemPlace.min.css`, and that results in not being able to find your files.

The fix is to add a leading `/` to your resource paths, eg:

```html
<link rel="stylesheet" th:href="@{/dist/css/ChemPlace.min.css}">
```

I applied this to all of the items in the layout file, and your other pages started looking correct.  I also spotted an image resource in your `fragments/sidenavigation.html` file, so you might want to correct that as well 🙂 

This sounds like the same issue you're describing in #191?  Although there you mention you have a leading `/`?

**Comment by navindercsb15** [comment]
Thanks a lot Sir for helping me out fixing this. It is working now.  I
Won't be repeating this silly mistake again. 😃

**Comment by navindercsb15** [comment]
Hey,

I just signed the petition ".@drharshvardhan @DrRPNishank @MoHFW_INDIA :
Close All Educational Institutions for Teachers and Other Staff
#KeepTeachersSafe" and wanted to see if you could help by adding your name.

Our goal is to reach 35,000 signatures and we need more support. You can
read more and sign the petition here:

http://chng.it/DcY8pvFVtX

Thanks!
Navinder
