### ISSUE TITLE
Question: I am having a hard time figuring out what LayoutDialect static initializer does

### ISSUE THREAD

**Issue by silkentrance** [ultraq/thymeleaf-layout-dialect#199]
```
class LayoutDialect extends AbstractProcessorDialect {

	static final String DIALECT_NAME = 'Layout'
	static final String DIALECT_PREFIX = 'layout'
	static final int DIALECT_PRECEDENCE = 10

	/**
	 * Apply object extensions.
	 */
	static {
		[
			// Context extensions
			IContextExtensions,

			// Model extensions
			IAttributeExtensions,
			ICloseElementTagExtensions,
			IModelExtensions,
			IProcessableElementTagExtensions,
			IStandaloneElementTagExtensions,
			ITemplateEventExtensions,
			ITextExtensions

		]*.apply()
	}
```

Searching for this using google did not give me any viable results, i.e. I searched for groovy static initializer object extensions and so on.

How does this work?

**Comment by silkentrance** [comment]
I should have read the code first :)

**Comment by ultraq** [comment]
Hey there, I'm glad you figured it out 🙂  I'll add that while the static initializer is the current way I'm adding extra methods to many of Thymeleaf's classes, I've since learned how to get Groovy's extension modules feature working and will likely opt for that in future.  It's currently sitting in one of the many branches I'm experimenting with, which you can see here if interested: https://github.com/ultraq/thymeleaf-layout-dialect/tree/extensions-module
