### ISSUE TITLE
Update to Groovy 3.x

### ISSUE THREAD

**Issue by wimdeblauwe** [ultraq/thymeleaf-layout-dialect#202]
This will avoid the problem of the reflective access warning (issue #188)

**Comment by mjeffrey** [comment]
It'd be nice to have this before Java 17 where this warning changes to an error (java17 removes the possibility to ignore the error). 

See https://blogs.oracle.com/javamagazine/java-runtime-encapsulation-internals

**Comment by ultraq** [comment]
Oh hey, thanks for letting me know that this was finally gonna be clamped down in Java 17.  I've had a Groovy 3 branch that needed some cleaning up to work correctly, so I've completed that work which closes this issue and am aiming for it to be in the next major version.

If anybody coming across this issue is interested, there is a `3.0.0-SNAPSHOT` version of the layout dialect that contains this upgrade.

**Comment by mjeffrey** [comment]
Thank you! Will try out the snapshot.
