### ISSUE TITLE
High vulnerability in Thymeleaf through 3.1.1.RELEASE

### ISSUE THREAD

**Issue by nunocarvalhog** [ultraq/thymeleaf-layout-dialect#239]
Hello 👋 

[CVE-2023-38286](https://nvd.nist.gov/vuln/detail/CVE-2023-38286)

Currently `thymeleaf-layout-dialect:3.2.1` is exposed because it uses the `thymeleaf/3.0.15.RELEASE`.

Could you please recover the https://github.com/ultraq/thymeleaf-layout-dialect/issues/228 to use a patched Thymeleaf version?

Thanks!

**Comment by ultraq** [comment]
Hey there, thanks for the report.  I can make a release of the layout dialect that has a dependency on the latest version of Thymeleaf, and in the interim anybody can manually specify the newer version of Thymeleaf  if they need (I believe a lot of people do this anyway since they select Thymeleaf first or use the version that's included in Spring Boot, before adding the layout dialect) as the layout dialect works with both 3.0 and 3.1 versions of Thymeleaf.

**Comment by ultraq** [comment]
I've just released 3.3.0 (should show up on Maven Central in a bit) which now has a dependency on Thymeleaf 3.1.2.RELEASE
