### ISSUE TITLE
Script tag order changing

### ISSUE THREAD

**Issue by pgmahoney** [ultraq/thymeleaf-layout-dialect#59]
I have a page where there are scripts which are dynamically added to the page:
```
<th:block th:each="externalScript : ${def.externals[scripts]}">
	<script type="text/javascript" th:src="${externalScript}"></script>
</th:block>
```

I would like the position of these scripts to be preserved in the head (when scripts are grouped together), but I can understand why they may not be. So, if they can't be is there a way to switch off the  grouping feature? The only solution I currently have is to revert to an older version of thymelead-layout-dialect.

**Comment by ultraq** [comment]
Done.  Created a 'head element sorting' strategy interface, and the dialect has 2 built-in that devs can choose from: `AppendingStrategy` which is the default behaviour and the same as how the layout dialect behaved before 1.2.6, and a `GroupingStrategy` which can be selected and is how the layout dialect behaved in 1.2.(6/7/8).

Now to create the documentation so that devs know how to switch between them, or create their own strategy.
