### ISSUE TITLE
fragment attribute rules

### ISSUE THREAD

**Issue by geemang2000** [ultraq/thymeleaf-layout-dialect#63]
What are the rules for an implementing page with (layout:decorator="layout") for common div attributes e.g. class?  I'd like the implementing page class attribute to overwrite. Is this possible? 

I have a layout with the following:
```
        <div layout:fragment="content"  class="ui segment attached">
            <h1>SAMPLE LAYOUT segment</h1>
        </div>
```
And the implementing page with:
```
    <div  layout:fragment="content" class="ui segment attached foo" ng-click="ss">
        <h1>THIS IS REAL: {{ message }}</h1>
    </div>
```
The result being:
```
<div class="ui segment attached" ng-click="ss">
        <h1>index: {{ message }}</h1>
    </div>
```

The ng-click hangs around as I want, but the class gets overwritten by the layout (not what I want).

**Comment by ultraq** [comment]
There aren't really any rules surrounding how this works as there haven't been the need to establish any or it hasn't been asked.  Right now, the code that does this copying of attributes does the following ([code here](https://github.com/ultraq/thymeleaf-layout-dialect/blob/master/Source/nz/net/ultraq/thymeleaf/LayoutUtilities.java#L124-L158)):
 - don't copy `layout:fragment` attributes from content to decorator
 - merge `th:with` attributes (content values going first, followed by decorator values)
 - copy any attributes from content to decorator that don't already exist in the decorator

An improvement could be made to enhance the merging rules.  Deciding on what those rules are will need some thought.

**Comment by ultraq** [comment]
Fixed by #71 - found merging bugs like this in the process which should be resolved by it

**Comment by ultraq** [comment]
I've updated the 1.3.0-SNAPSHOT with the fix for this issue

**Comment by csavory** [comment]
we were using Layout Dialect 1.2.9 and have now upgraded to 1.3.1.

We had some global classes being set in the layout.html like this:
```
<div id="main-content" class="main container-fluid page-host" layout:fragment="content">Fake content</div>
```
Which are now overridden by the fragment:
```
<div layout:fragment="content" class="container">
```

I realize I can just remove the ```class="container"``` on the fragment and it will work like I want it to, but i'm looking for a variable that I can set on the layout.html fragment to see that these attributes win.

**Comment by ultraq** [comment]
What is the result that you're aiming for @csavory?

The behaviour in 1.3 is for the content attributes to override any layout attributes (the only exception being `th:with` attributes getting merged because they can contain information to be passed around).  Versions older than 1.3 had no rules about attributes (as discovered by the original poster) and so were a bit of a mixed bag, so I set to fix that and make them consistent with the fragment replacement rules (content > layout).

For your case, is it that you're wanting the layout to win?  Is it always the case that you want the layout to win for `class` attributes?  Would a merged result on class attributes work?
