### ISSUE TITLE
data-layout-include doesn't work properly in title

### ISSUE THREAD

**Issue by chrylis** [ultraq/thymeleaf-layout-dialect#64]
I'm trying to put together a shell page that will render "modal" dialogs as full standalone pages. As part of this, I want the modal's title text (in some normal body element) to be put in the page title.

In ordinary Thymeleaf, I can specify

    <title data-th-include="widgets/form/login :: widget-title">Modal</title>

and this replaces "Modal" with the contents of `data-th-fragment="widget-title"`. However, I'm using a layout decorator, and this approach squashes my decorator (I end up with `::widget-title` as the entire title text). If I replace `th` with `layout` in both templates, the replacement does not happen at all.

Desired behavior: I can eat my cake and have it too; `data-layout-include` in the title grabs the contents of the matching fragment *and* runs it through the decorator.

**Comment by ultraq** [comment]
Because of the `title-pattern` processor, I create a totally new `title` element with the merged result, thus removing things like other processors.  I'll try to figure out how I can include other attributes, like other processors, in the final result.

**Comment by ultraq** [comment]
Actually... @chrylis, are you asking if the title can be fetched, and then included as input to a `title-pattern` processor as well?

**Comment by ultraq** [comment]
Done :)  I've just updated a 1.3.0-SNAPSHOT version of the layout dialect with a fix for this issue.  If you could give it a try, let me know if it's still not working as expected.

**Comment by chrylis** [comment]
I will try soon. Since I realized I never explained my use case here: I have some dialogs that are logically modals, such as the standard login form. However, I'm a firm believer in (1) not cluttering up HTML with unnecessary hidden dialogs and (2) making as much of the site usable with NoScript as possible, so I have a layout shell that takes the "content" part of a Bootstrap modal and renders it on a full page. I'm wanting to use the "modal title" as the page title when I do this.

**Comment by chrylis** [comment]
I've tested by rolling over to 1.3.0-SNAPSHOT, and I now have a regression where any sort of dynamic interaction in the title element (such as `<title data-th-text="${stuff}" />`) turns off the title decorator pattern entirely.

**Comment by chrylis** [comment]
Here's a self-contained HTML file:

```
<html data-layout-decorator="layout/gallery-layout">
<head>
    <title data-layout-fragment="widget-title"
        data-th-text="|Image download ${#strings.isEmpty(key.note) ? '' : (' (' + key.note + ')')}|">Download link</title>
</head>

<body>
    <section data-layout-fragment="page-content">
        <div class="col-xs-12 col-md-8 col-md-offset-2">
            <div class="panel panel-primary">
                <div class="panel-heading">
                    <h3 class="panel-title"><span data-layout-include="::widget-title" /></h3>
                </div>
            </div>
        </div>
    </section>
</body>
</html>
```

I expect the `span` to fill with the results of the `data-th-text` expression, but instead the contents are "Download link".

**Comment by ultraq** [comment]
Thanks for the test case, I'll throw that in there and see what might be wrong.

**Comment by ultraq** [comment]
So I just spent a while trying to figure this one out, but if the simplified test case I have is right (https://github.com/ultraq/thymeleaf-layout-dialect/blob/dev/Tests/nz/net/ultraq/thymeleaf/tests/decorators/TitlePattern-DynamicContent.thtest) then this never used to work before (tried on the 1.2 branch of the layout dialect).  `layout:include` works mostly the same as `th:include`, in that it goes to the template repository to get the node referenced by the selector.  Because it goes to the template repository, rather than scanning the current document, it never gets the processed title with the updated values, but rather a fresh copy of the node from the template repository.

Even if you broke it down to a simple `th:include`/`th:fragment` test:

```html
var blah = "blah"
...
<div th:fragment="test" th:text="${blah}">Something</div>
...
<div id="result" th:include="test"></div>
```

The result would be that the "result" div would have "Something" in it, instead of "blah".

**Comment by ultraq** [comment]
OK, so given the convo between this issue and the other, I only went so far as to implement the ability to do this:

```html
<title data-layout-include="title-from-somewhere-else">...</title>
```

Not:

```html
<div data-layout-include="title-element-after-it-has-been-processed">...</div>
```

I only thought you were asking about the first as that was the example you gave in the original post.  If you're also asking to do the second, then that's another issue, which will prove a bit more difficult to solve without breaking the existing functionality of `layout:include` (and because of the comment I made above).

**Comment by ultraq** [comment]
New issue created to continue discussion of your more recent comments: #76
