### ISSUE TITLE
Expression for title is used literally and not evaluated

### ISSUE THREAD

**Issue by chrylis** [ultraq/thymeleaf-layout-dialect#66]
When I have the following tag in my file:

```
<title data-th-text="|${work.title} by ${mainArtist.displayName}|">Work by Artist</title>
```

The expression is used literally by the layout decorator instead of being evaluated, leaving a title of 

```
|${work.title} by ${mainArtist.displayName}| | ArtSquare
```

instead of the correct result. A simple `"${work.title}"`, without the pipe formatting, is also rendered literally. I'm using Thymeleaf 2.1.4 and TLD 1.2.8 with Spring MVC 4.1.6 (Spring Boot 1.2.3).

**Comment by chrylis** [comment]
Does the milestone tag mean that this won't be fixed for the Thymeleaf 2.x series?

**Comment by ultraq** [comment]
I remember taking a quick look when you first raised the issue and couldn't figure it out then, thinking it was related to some other title-related bugs that I'm saving for the next major version, so I attached it to the next release milestone.

I've just given it some more thought and I _should_ be able to fix this in a patch version... it probably won't be elegant though because the only solution that comes to mind is doing a second pass of the expression parser over the merged title which, a) feels inefficient, and b) I wonder if the context of the merged title will still have the information needed to create the proper result.

I'll try come up with something better, but if all else fails I'll give the second-pass idea a chance, releasing a patch version of the layout dialect for this.

**Comment by chrylis** [comment]
If it's going to have to wait I'll work around, I just wanted to see whether I needed to special-case it in my code.

**Comment by ultraq** [comment]
I'll aim to get something done and released before the end of this weekend, so if that's a bit far for you then go ahead and work around it for now.

**Comment by chrylis** [comment]
This weekend is plenty fast enough. I was just not sure whether a fix would need to wait for Thymeleaf 3.

**Comment by ultraq** [comment]
Started trying to create a test case for this, but when I make something based off what you've posted, it passes.  I must be missing something, so any chance you could show me more of your HTML code, mainly the head/title tags of both decorator and content pages?  This is the test case I made: https://github.com/ultraq/thymeleaf-layout-dialect/blob/master/Tests/nz/net/ultraq/thymeleaf/tests/decorator/TitlePattern-ParseExpressions.thtest

**Comment by chrylis** [comment]
I'll try to get that to you; it may take a bit to simplify.

**Comment by chrylis** [comment]
`work.html`:

```html
<!DOCTYPE html>
<html data-layout-decorator="layout/gallery-layout">
<head>
<title data-th-text="|__${work.title}__ by ${mainArtist.displayName}|">Work by Artist</title>
```

`layout/gallery-layout.html`:

```html
<!DOCTYPE html>
<html>
<head>
    <title data-layout-title-pattern="$CONTENT_TITLE | $DECORATOR_TITLE">ArtSquare</title>
```

Resulting rendered HTML:

```html
<!DOCTYPE html>

<html>
<head>
    
    <title>|__${work.title}__ by ${mainArtist.displayName}| | ArtSquare</title>
```

**Comment by chrylis** [comment]
Same behavior if I attempt to use `data-th-inline="text"` and the bracket notation inside the title tag.

**Comment by chrylis** [comment]
This is a bug with the `__` interpolation upstream.

**Comment by chrylis** [comment]
https://github.com/thymeleaf/thymeleaf/issues/366

**Comment by ultraq** [comment]
Ah, cool.  Thanks for investigating! :smiley:
