### ISSUE TITLE
Groovy dependency

### ISSUE THREAD

**Issue by gseifert** [ultraq/thymeleaf-layout-dialect#86]
The latest version now has a groovy dependency.  Many projects avoid any dependency on groovy.  See http://stackoverflow.com/questions/24403691/is-writing-a-library-with-a-dependency-on-groovy-a-good-idea

So if I don't want to include a dependency on groovy, I guess I am stuck on version 1.2.x and miss out on some bug fixes in 1.3+?

**Comment by ultraq** [comment]
There's a dependency on Groovy because it was rewritten in Groovy - I don't think I can avoid the dependency if it's written in that language :P

I made the move to Groovy for many reasons that are mostly personal opinion/preference/choice, the biggest one being that I found maintaining the layout dialect as a Java project a chore and so stopped enjoying working on it.  I still like the JVM, but am not as much a fan of Java as I used to be.

So to answer your question: yes, if you don't want to have Groovy in your dependency graph, then don't include 1.3+.  1.2.9 is still in plain Java, but I don't see myself updating the 1.2 branch any more.
