### ISSUE TITLE
maven transitive groovy dependency

### ISSUE THREAD

**Issue by drobert** [ultraq/thymeleaf-layout-dialect#88]
When pulling down the latest dialect artifact from maven central, it includes a transitive dependency on the groovy lib. I believe this should only be an artifact at compile time of the lib, but not for downstream consumers of the lib.

**Comment by drobert** [comment]
I may re-open this but this may be a local environment snafu. Closing for now.

**Comment by drobert** [comment]
Confirmed. See the pom file from maven central as seen here:
http://central.maven.org/maven2/nz/net/ultraq/thymeleaf/thymeleaf-layout-dialect/1.3.1/thymeleaf-layout-dialect-1.3.1.pom

**Comment by ultraq** [comment]
I remember trying to check that it was a compile time only dependency, but remember a test where if I don't include it then I'd get `NoClassDefFoundError`s.  Do you think you'd be able to confirm this if you're working on a Java project by excluding the dependency in your maven config and seeing if your program still runs?

**Comment by drobert** [comment]
It's working for me so far, but I haven't done any particularly exhaustive tests. No immediate explosions. If the downloadable 1.3.1 jar works, then it ought to work in maven as well without a transitive dependency. I'll post back if any issues come up, but I'll be on vacation for the next 10 days or so.

**Comment by ultraq** [comment]
So I fired up the [Thymeleaf + Spring PetClinic example app](https://github.com/thymeleaf/thymeleafexamples-petclinic) and added the layout dialect to the template engine config.  Upon startup I got exceptions in the startup log because it couldn't find `org.groovy.lang.Object` or something like that.  When you're back from your vacation, could you see if you get those too?

I'll try on a non-Spring project as well to see if that makes a difference.
